[package]
name = "sales_record"
version = "1.0.0"
authors = ["cnerd"]

[addresses]
sales_record = "0x1010"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
